# Generated by Django 3.1.4 on 2020-12-09 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='poost',
            options={'verbose_name': 'poost', 'verbose_name_plural': 'poosts'},
        ),
    ]
