# Generated by Django 3.1.4 on 2020-12-09 15:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_auto_20201209_1338'),
    ]

    operations = [
        migrations.AddField(
            model_name='poost',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
