# Generated by Django 3.1.4 on 2020-12-12 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_poost_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='poost',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
